### ISSUE TITLE
Allow for fixed or exponential back-off between request retries

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#102]
The automatic request retrying feature aims to mask transient request failures. This approach would be more effective if subsequent requests were delayed slightly to allow time for the cause behind the transient failure to alleviate itself. This delay could be a fixed delay (200 ms between attempts) or an exponential back-off (200 ms, 400ms, 800ms, 1.6s, etc).

## Potential Implementation
```dart
enum RetryBackOff { exponential, fixed }

request.autoRetry
  ..backOffMethod = RetryBackOff.fixed /* or */ RetryBackOff.exponential
  ..backOffDuration = new Duration(milliseconds: 200);
```

Thoughts? @trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf

**Comment by maxwellpeterson-wf** [comment]
+1 I like it

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
Thoughts on using 

```dart
request.autoRetry
  ..backOffMethod = RetryBackOff.none  // a third enum option!
```
instead of
```dart
request.autoRetry
  ..backOffMethod = RetryBackOff.fixed
  ..backOffDuration = new Duration(milliseconds: 0);
```
for immediate retry?

**Comment by evanweible-wf** [comment]
Yeah I'm fine with that. What do we want the default to be?

**Comment by maxwellpeterson-wf** [comment]
I vote default should be `RetryBackOff.none` (meaning by default it does the same thing that it would do now)

**Comment by evanweible-wf** [comment]
I agree
