### ISSUE TITLE
CP-2246 Allow mock configuration with fallback to real implementation

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#125]
Although the mock configuration was intended for testing, it's also useful for local development. Authentication in an application could be mocked out allowing a faster local dev cycle. However, as currently implemented, `configureWTransportForTest()` is all or nothing. Consider the scenario where an application wants to mock authentication requests but send real requests for a local service - this is currently not possible.

Because the test configuration is platform-independent, it should be possible to allow a fallback to a real implementation (browser or VM). This would require some refactoring, but should be able to be done in a backwards-compatible way.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
Added in #222.
