### ISSUE TITLE
CP-2242 Use null-aware operators

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#144]
The minimum SDK constraint has been 1.9.0 since this library was originally created, and as such we've avoided using null-aware operators. Dart 1.17.0 is about to be released, so it's probably time to bump that minimum SDK version. Once we do so, we should leverage null-aware operators to simplify some of the code.

**Comment by maxwellpeterson-wf** [comment]
Which version were you thinking? ^1.13.0?

**Comment by evanweible-wf** [comment]
Yeah ^1.13.0

**Comment by evanweible-wf** [comment]
Merged into the 3.0.0-wip branch in #221.
