### ISSUE TITLE
Support unregistering mock transport handlers

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#167]
Currently, the only way to unregister a mock HTTP or WS handler is to call `MockTransports.reset()`, but this more destructive than necessary. There may be libraries built on top of w_transport that may want to support a similar "reset" function without destroying mock expectations & handlers setup by other consumers of w_transport.

First instinct is to change the signature of `when()` and `whenPattern()` methods to return a handle with a single `unregister()` method similar to the `Timer` instance you get when setting a timeout or interval that has a `cancel()` method.

**Comment by maxwellpeterson-wf** [comment]
+1
