### ISSUE TITLE
CP-2236 Simplify entry point names

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#172]
Currently we have:

`package:w_transport/w_transport.dart`
`package:w_transport/w_transport_browser.dart`
`package:w_transport/w_transport_mock.dart`
`package:w_transport/w_transport_vm.dart`

For the last three, the "w_transport" prefix isn't really necessary. The following would be cleaner:

`package:w_transport/w_transport.dart`
`package:w_transport/browser.dart`
`package:w_transport/mock.dart`
`package:w_transport/vm.dart`

We could make this change in a backwards compatible way, and a simple find/replace would fix the deprecation warnings. Additionally, we'd only change non-main entry points, which means there wouldn't be that many affected usages in consumer projects.

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
Merged to 3.0.0-wip in #198
