### ISSUE TITLE
3rd time is the charm

### ISSUE THREAD

**Issue by travisreed-wf** [Workiva/w_transport#178]

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://joe2-dot-w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/178/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
@travisreed-wf am I okay to close this now?

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': '3rd time is the charm'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': '3rd time is the charm'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': '3rd time is the charm'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole2-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': '3rd time is the charm'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole2-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': '3rd time is the charm'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.
