### ISSUE TITLE
Investigate intermittent autoRetry jitter test failures

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#186]
A couple of the autoRetry jitter tests are failing intermittently. It's most likely just a matter of timing - the backoff factors and wait durations may need to be increased to improve the tolerance.

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/186/addTicketToTitle'>here</a> to have Rosie create one for you.
