### ISSUE TITLE
Add isDone or isCompleted getter to BaseRequest

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#187]

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/187/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
@ericlarssen-wf @kevinfrommelt-wf I'm making a PR to add an `isDone` boolean to all of the request classes - is that sufficient for your use case? Or do you also need a getter to determine if the request was canceled?

**Comment by rmconsole2-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': 'Add isDone or isCompleted getter to BaseRequest'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': 'Add isDone or isCompleted getter to BaseRequest'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rmconsole3-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': 'Add isDone or isCompleted getter to BaseRequest'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this issue.

I sent the following data to JIRA:
`{'issuetype': {'name': u'Task'}, 'project': {'key': u'CP'}, 'description': '', 'components': [{'name': u'w_transport'}], 'summary': 'Add isDone or isCompleted getter to BaseRequest'}`

I received the following data from JIRA:
`{"errorMessages":[],"errors":{"description":"Description is required."}}`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.
