### ISSUE TITLE
CP-2294 Increase minimum SDK version to 1.14.0

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#188]
Increase minimum SDK version to 1.14.0

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/188/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Merged to 3.0.0-wip in #197
