### ISSUE TITLE
CP-2445 Deprecate unnecessary mock classes

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#207]
Currently we're exporting all of the mock classes in the mock entry point, but only a few of them are necessary. We should deprecate the ones that are not necessary so that we can remove them from the entry point in the 4.0.0.

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/207/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Fixed in #224.
