### ISSUE TITLE
CP-2610 Add separate test util class for acting as web socket server

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#214]
Currently, the `MockWSocket` class implements the `WebSocket` w_transport class _and_ includes API methods for controlling the behavior of the mock web socket server. This is confusing because it combines responsibility of the client and server into a single class.

Instead, consumers should use `WebSocket` as usual (with mocks installed) and we should introduce a new class for controlling behavior of a mock web socket server. The name could be `MockWebSocketServer` or something similar.

This should happen at the same time as #207.

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/214/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
Added in #224.
