### ISSUE TITLE
CP-3090 Canceling a request leads to all retry attempts failing as "canceled" (but only one request is sent)

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#241]
Need to confirm this one.

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/241/addTicketToTitle'>here</a> to have Rosie create one for you.
