### ISSUE TITLE
Relative requests to baseUri

### ISSUE THREAD

**Issue by unibeck** [Workiva/w_transport#260]
The documentation for `HttpClient` states that the `baseUri` is inherited by all requests made by that client. Though the documentation on a `Request.get()` states that if a uri is given then it ignores the `baseUri` and instead makes the request to the uri given. I propose that if a uri is given in a relative format s.t. there is no forward (root) slash at the beginning of the uri, then it should be appended to the `baseUri`.

For example, if the the application is serving on `localhost:8080` and I set `_http.baseUri` to `localhost:8081` then,
`Response response = await _http.newRequest().get(uri: Uri.parse('management/info'));` would make a request to `localhost:8081/management/info`. Note the lack of root slash at the start of the uri. While 
Response response = await _http.newRequest().get(uri: Uri.parse('/management/info')); would make a request to `localhost:8080/management/info`.

Currently though both of the above examples make a request to `localhost:8080/management/info`. If this does become a feature, then checks for uri should not only look for the root slash but also if it starts with a protocol, hostname, and port. Also since baseUri is optional, it a Uri is relative then through some exception denoting that a relative endpoint isn't supported without a baseUri.

What do you guys think?

**Comment by evanweible-wf** [comment]
The idea when we implemented this was that "uri" refers to the entire identifier, not any particular part of it. With that in mind, we decided that setting the `.uri` field on a request or supplying a value for the `uri` optional param when calling `get()` would be interpreted as the consumer intentionally setting the entire uri.

We were okay with this because we also chose to make all of the request classes mixin [`FluriMixin`](https://www.dartdocs.org/documentation/fluri/1.2.1/fluri/FluriMixin-class.html) so that the consumer also has access to a variety of methods that can augment or modify the uri:

https://www.dartdocs.org/documentation/fluri/1.2.1/fluri/FluriMixin-class.html

With your example, you could accomplish building onto your `baseUri` in a couple different ways:

```dart
Request request = _http.newRequest()
  ..path = '/management/info';
Response response = await request.get();

Request request = _http.newRequest()
  ..appendToPath('/management/info');
Response response = await request.get();
```

Would that be a reasonable solution?

I'm not totally against the idea of checking the given `uri` to see if it is absolute or relative and reacting accordingly, but it would be a change in behavior that could be seen as a breaking change. There may be certain usages of the `uri` setter or param that consumers have employed expecting it to completely overwrite any existing uri, and this change would break that expectation.

**Comment by unibeck** [comment]
Yeah that solution is fine, I was using `Response response = await _http.newRequest().get(
          uri: Uri.parse('${_http.baseUri}/management/info'));` in the mean time. You suggestions makes more sense as it uses the API as intended.

I'm also fine with how the current API works, just seems like baseUri implies that there will be concatenation and along with how the document says the the baseUri is inherited; it muddies up the true purpose of baseUri

**Comment by maxwellpeterson-wf** [comment]
Another option could be to add an optional `path` param to `get()` and other request methods so that you could accomplish the shorter syntax:

```dart
Response response = await _client.newRequest().get(path: '/management/info');
```

**Comment by unibeck** [comment]
@maxwellpeterson-wf  Would your proposed `path` parameter support relative, absolute, or both path types? Since the `uri` param is solely for absolute paths, `path` would not have to support that implementation and at that point a more explicit param name would be useful like `relativePath`.

**Comment by evanweible-wf** [comment]
I'm open to that idea, although we'd have to decide on which subset of the `FluriMixin` modifiers to support. And @unibeck my guess is that we would follow the same pattern that Fluri uses by treating setters like `path` or `host` or `scheme` as complete overwrites for _that specific part of the uri_.

That being said, given that there is already a way to do this, I'm a bit hesitant to add another avenue.

The `uri` param exists as a convenience for very simple requests that can be one-lined, but for anything beyond that I generally feel that the fluent-style request builder option should be used.

**Comment by evanweible-wf** [comment]
As a side note – I will open up another issue to address the ambiguity in the documentation of `baseUri` by explicitly calling out this caveat, because that should be addressed regardless. Thanks for pointing that out @unibeck

**Comment by unibeck** [comment]
Awesome, I fully agree with the first paragraph! 

Well you can fluently build the request object with the specified path, but for finer grain control having them as a named parameter in the HTTP methods would complete them more. For instance you can't fluently build a request with headers, but you can pass them to the `get()` method. So maybe I don't understand as to why you guys allow some control in the HTTP methods (`header` param) and some in the `Request` object itself (`appendToPath()`) and then have some overlap.

And thanks, I think the documentation is overall amazing. Just that this misunderstanding had me stuck for an hour or so - clearing that up might help others in the future.

**Comment by evanweible-wf** [comment]
@unibeck the params to the request methods like `get()` are just there for convenience for simple requests, but everything that can be done via the params can also be done directly on the request object. There is a `Map headers` field on every request object that can be set or modified directly:

```dart
var request = new Request()
  ..headers = {'x-custom-header': 'value'}; // sets the entire headers map;

var request = new Request()
  ..headers['x-custom-header'] = 'value'; // sets a single header

var commonHeaders = {'header1': 'value', 'header2': 'value'};
var request = new Request()
  ..headers.addAll(commonHeaders);
```

Every request class (`Request`, `JsonRequest`, etc.) extends `BaseRequest`. You can see all of the APIs and fields that are available on `BaseRequest` here:
https://www.dartdocs.org/documentation/w_transport/3.0.3/w_transport/BaseRequest-class.html

**Comment by unibeck** [comment]
Hmm, when I checked earlier `headers` was a member variable of the `HttpClient`. Maybe I was doing something wrong because the docs that you linked clearly state that `headers` is a member variable of the `BaseRequest` class. :) Sorry about that.

**Comment by evanweible-wf** [comment]
@unibeck the `HttpClient` class also has a `headers` field (https://www.dartdocs.org/documentation/w_transport/3.0.3/w_transport/HttpClient-class.html) – headers added to that map will be inherited by any requests created from that client
