### ISSUE TITLE
WP-4636 DDC support

### ISSUE THREAD

**Issue by unibeck** [Workiva/w_transport#274]
Hey guys,
Running `pub build --web-compiler=dartdevc` while having `dependencies: w_transport: ^3.0.0` will fail. The gist is what pub outputs https://gist.github.com/unibeck/40ba1effe6c4ecdbe4e9e13b69bd7f24. Let me know if you need anymore information.

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/274/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/274/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/274/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
Hi @unibeck, we just published v3.0.4 yesterday morning which includes an update to the strong-mode-compliant version of `sockjs_client` (v0.3.2). Running a `pub upgrade w_transport` should fix that for you.

**Comment by unibeck** [comment]
Oh that's awesome, thanks! Sorry for the wasted time!
