### ISSUE TITLE
Tag 2.10.0 missing dependecy

### ISSUE THREAD

**Issue by valakis** [Workiva/w_transport#285]
The `lib/src/web_socket/global_web_socket_monitor.dart` using the `meta` package, but its not added to the `pubspec.yaml`. It's working fine with serve, but during a pub build, its failing.

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click a type to create one automatically: <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/285/addTicketToTitle/Task/">Task</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/285/addTicketToTitle/Bug/">Bug</a>, <a href="https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_transport/285/addTicketToTitle/Improvement/">Improvement</a>

**Comment by evanweible-wf** [comment]
Thanks for reporting this @valakis, I've got a PR to fix this here:
https://github.com/Workiva/w_transport/pull/286

Out of curiosity, is there anything preventing you from upgrading to v3.x?

**Comment by valakis** [comment]
I'm lack of time, but the upgrade is planed.

**Comment by evanweible-wf** [comment]
Okay no problem, I was just curious! The upgrade should be backwards compatible, so you may be able to upgrade without making any changes right away (see https://github.com/Workiva/w_transport/blob/master/docs/upgrade-guides/v3.0.0.md).

We've just released 3.1.1 and 2.10.1 with the `meta` package dependency issue fixed. Thanks again!
