### ISSUE TITLE
STOMP over SockJS?

### ISSUE THREAD

**Issue by unibeck** [Workiva/w_transport#289]
I don't see in the docs nor the API of a way to connect to a stomp message broker with SockJS. Am I missing something or does `w_transport` not support this (yet)?

**Comment by evanweible-wf** [comment]
Currently, w_transport doesn't support STOMP over SockJS. Do you have any examples of this setup in Dart or JS that you could point me to? I'm not very familiar with it

**Comment by unibeck** [comment]
I couldn't find any for Dart, but there are a few JS ones on NPM. Here are the specs https://stomp.github.io/index.html

**Comment by evanweible-wf** [comment]
From some quick reading, it appears that most STOMP clients will either create the WS connection for you or allow a [custom WS object to be supplied via a factory](https://stomp-js.github.io/stomp-websocket/codo/extra/docs-src/sockjs.md.html). Either way, it looks like it is concerned with building a more sophisticated transport protocol on top of a WS or WS-like connection, which would be outside the scope of `w_transport`. If there were a Dart client out there or if you have an interest in writing one, I'm definitely open to doing what we can to make `w_transport` a compatible option for the WS part. Just let me know!

**Comment by unibeck** [comment]
https://github.com/Apaq/StompDart or https://pub.dartlang.org/packages/stomp. Though these packages haven't been updated in awhile and I'm not sure how well they're tested.
