### ISSUE TITLE
Consider throwing an error if one attempts to use w_transport without configuring first

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/w_transport#70]
## Ultimate problem
If one attempts to use w_transport without first configuring it :
`configureWTransportForBrowser`, `configureWTransportForServer` or `configureWTransportForTest`, requests aren't made, but the consumer isn't informed of why.

Perhaps we should throw an error?

**Comment by evanweible-wf** [comment]
If this is accurate, it's a bug. Constructing a request should throw if w_transport hasn't been configured yet. Are you using `WHttp` directly?

**Comment by dustinlessard-wf** [comment]
@evanweible-wf , here's what I'm doing : https://github.com/Workiva/app_intelligence/pull/11/files#diff-1e4224ad6124d5c0229659e491ff9cb7R33

Here's where I noticed this behaviour: 
https://github.com/Workiva/app_intelligence/pull/11/files#diff-0fe51d72205a0c68459fe94fb7a001cbR35
(If we remove line 44, no errors are observed)

I realize that I should have a catchError, but since we can't guarantee that consumers will take that precaution either, perhaps we can consider if there's a way to inform them of a failure in configuring w_transport?

**Comment by evanweible-wf** [comment]
Hmm.. without the catchError the exception should propagate to the root zone and you should still see it. That's strange. For now, I'd say sit on it and I'll hopefully have w_transport ready for it's next release soon, and I would imagine this would be fixed. If not, I'll dig in and see what's going on

**Comment by evanweible-wf** [comment]
@dustinlessard-wf if you get a chance, could you upgrade to 2.0.0 and let me know if this is still a problem?

**Comment by evanweible-wf** [comment]
@dustinlessard-wf have you had a chance to try this out?

**Comment by dustinlessard-wf** [comment]
@evanweible-wf , will do today.

**Comment by dustinlessard-wf** [comment]
@evanweible-wf , wasn't able to test this as:
```Incompatible version constraints on w_transport:
- app_intelligence depends on version 2.0.0
- w_session 2.0.0 depends on version ^1.0.1```

**Comment by evanweible-wf** [comment]
ah shoot, I keep forgetting that.

**Comment by evanweible-wf** [comment]
I ran into this in testing w_session, and it seems to be working as expected. I'm going to close this. If you run into it again, just reopen this issue.
