### ISSUE TITLE
Support request retrying

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_transport#95]
It would be useful if all requests and `Client` had an API to enable request retrying.

## Criteria
- There should be criteria (configurable) that determines whether or not a failed request should be retried based on the status code, request method, etc.
  - By default, mutation requests should not be retried to avoid issues with idempotence.
  - 500 and 502 should be retried because they could be transient.
- The number of retries to attempt should have a sensible default and be configurable.
- There should be an API for retry-related info like `bool get wasRetried`, `int get numRetries`, `Iterable get retryFailures`.
  - These should live on the request instance so that they are always available. This means it will also need to be on the `FinalizedRequest` class so that response interceptors have access.
  - Interceptors can use this information to prioritize requests or to record analytics.
- If a request exceeds the maximum number of retries, an explanation should be included in the string version of the `RequestException`

## Questions
- Should `timeoutDuration` apply to each request attempt or to the process as a whole?
  - Answer: each attempt

@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf

**Comment by maxwellpeterson-wf** [comment]
I vote each attempt.

**Comment by evanweible-wf** [comment]
+1
